#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Build Lean's OpenWrt for Orange Pi Zero

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # ========================固件定制部分========================
          # 
          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 
          # 以下为定制化固件选项和说明:
          #
          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #
          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 
          cat >> .config <<EOF
           CONFIG_TARGET_sunxi=y
           CONFIG_TARGET_sunxi_cortexa7=y
           CONFIG_TARGET_sunxi_cortexa7_DEVICE_xunlong_orangepi-zero=y
           CONFIG_ARIA2_BITTORRENT=y
           CONFIG_ARIA2_NOXML=y
           CONFIG_ARIA2_OPENSSL=y
           CONFIG_ARIA2_WEBSOCKET=y
           CONFIG_DRIVER_11N_SUPPORT=y
           CONFIG_DRIVER_11W_SUPPORT=y
           CONFIG_LIBCURL_COOKIES=y
           CONFIG_LIBCURL_FILE=y
           CONFIG_LIBCURL_FTP=y
           CONFIG_LIBCURL_HTTP=y
           CONFIG_LIBCURL_NO_SMB="!"
           CONFIG_LIBCURL_OPENSSL=y
           CONFIG_LIBCURL_PROXY=y
           CONFIG_NGINX_HEADERS_MORE=y
           CONFIG_NGINX_HTTP_ACCESS=y
           CONFIG_NGINX_HTTP_AUTH_BASIC=y
           CONFIG_NGINX_HTTP_AUTOINDEX=y
           CONFIG_NGINX_HTTP_BROWSER=y
           CONFIG_NGINX_HTTP_CACHE=y
           CONFIG_NGINX_HTTP_CHARSET=y
           CONFIG_NGINX_HTTP_EMPTY_GIF=y
           CONFIG_NGINX_HTTP_FASTCGI=y
           CONFIG_NGINX_HTTP_GEO=y
           CONFIG_NGINX_HTTP_GZIP=y
           CONFIG_NGINX_HTTP_LIMIT_CONN=y
           CONFIG_NGINX_HTTP_LIMIT_REQ=y
           CONFIG_NGINX_HTTP_MAP=y
           CONFIG_NGINX_HTTP_MEMCACHED=y
           CONFIG_NGINX_HTTP_PROXY=y
           CONFIG_NGINX_HTTP_REFERER=y
           CONFIG_NGINX_HTTP_REWRITE=y
           CONFIG_NGINX_HTTP_SCGI=y
           CONFIG_NGINX_HTTP_SPLIT_CLIENTS=y
           CONFIG_NGINX_HTTP_SSI=y
           CONFIG_NGINX_HTTP_UPSTREAM_HASH=y
           CONFIG_NGINX_HTTP_UPSTREAM_IP_HASH=y
           CONFIG_NGINX_HTTP_UPSTREAM_KEEPALIVE=y
           CONFIG_NGINX_HTTP_UPSTREAM_LEAST_CONN=y
           CONFIG_NGINX_HTTP_USERID=y
           CONFIG_NGINX_HTTP_UWSGI=y
           CONFIG_NGINX_NAXSI=y
           CONFIG_NGINX_PCRE=y
           CONFIG_OPENSSL_WITH_COMPRESSION=y
           CONFIG_OPENSSL_WITH_DTLS=y
           CONFIG_OPENSSL_WITH_EC2M=y
           CONFIG_OPENSSL_WITH_NPN=y
           CONFIG_OPENVPN_openssl_ENABLE_DEF_AUTH=y
           CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
           CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
           CONFIG_OPENVPN_openssl_ENABLE_LZO=y
           CONFIG_OPENVPN_openssl_ENABLE_MULTIHOME=y
           CONFIG_OPENVPN_openssl_ENABLE_PF=y
           CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
           CONFIG_OPENVPN_openssl_ENABLE_SERVER=y
           CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
           CONFIG_PACKAGE_MAC80211_DEBUGFS=y
           CONFIG_PACKAGE_MAC80211_MESH=y
           CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
           CONFIG_PACKAGE_amule=y
           CONFIG_PACKAGE_aria2=y
           CONFIG_PACKAGE_ariang=y
           CONFIG_PACKAGE_automount=y
           CONFIG_PACKAGE_autosamba=y
           CONFIG_PACKAGE_baidupcs-web=y
           CONFIG_PACKAGE_bash=y
           CONFIG_PACKAGE_bird1-ipv4=y
           CONFIG_PACKAGE_bird1-ipv4-uci=y
           CONFIG_PACKAGE_bird1-ipv6=y
           CONFIG_PACKAGE_bird1-ipv6-uci=y
           CONFIG_PACKAGE_blkid=y
           CONFIG_PACKAGE_btrfs-progs=y
           CONFIG_PACKAGE_ca-bundle=y
           CONFIG_PACKAGE_cgroupfs-mount=y
           CONFIG_PACKAGE_chinadns-ng=y
           CONFIG_PACKAGE_containerd=y
           CONFIG_PACKAGE_coreutils-nohup=y
           CONFIG_PACKAGE_curl=y
           CONFIG_PACKAGE_dnscrypt-proxy=y
           CONFIG_PACKAGE_dnscrypt-proxy-resolvers=y
           CONFIG_PACKAGE_dnsforwarder=y
           CONFIG_PACKAGE_docker-ce=y
           CONFIG_PACKAGE_fdisk=y
           CONFIG_PACKAGE_frpc=y
           CONFIG_PACKAGE_haproxy=y
           CONFIG_PACKAGE_hostapd-common=y
           CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
           CONFIG_PACKAGE_iptables-mod-extra=y
           CONFIG_PACKAGE_iptables-mod-ipopt=y
           CONFIG_PACKAGE_iw=y
           CONFIG_PACKAGE_kcptun-client=y
           CONFIG_PACKAGE_kmod-br-netfilter=y
           CONFIG_PACKAGE_kmod-cfg80211=y
           CONFIG_PACKAGE_kmod-crypto-crc32c=y
           CONFIG_PACKAGE_kmod-dax=y
           CONFIG_PACKAGE_kmod-dm=y
           CONFIG_PACKAGE_kmod-eeprom-93cx6=y
           CONFIG_PACKAGE_kmod-fs-exfat=y
           CONFIG_PACKAGE_kmod-fs-ext4=y
           CONFIG_PACKAGE_kmod-fs-vfat=y
           CONFIG_PACKAGE_kmod-fuse=y
           CONFIG_PACKAGE_kmod-ifb=y
           CONFIG_PACKAGE_kmod-ikconfig=y
           CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
           CONFIG_PACKAGE_kmod-ipt-extra=y
           CONFIG_PACKAGE_kmod-ipt-ipopt=y
           CONFIG_PACKAGE_kmod-lib-crc16=y
           CONFIG_PACKAGE_kmod-lib-crc32c=y
           CONFIG_PACKAGE_kmod-mac80211=y
           CONFIG_PACKAGE_kmod-nf-ipvs=y
           CONFIG_PACKAGE_kmod-nls-base=y
           CONFIG_PACKAGE_kmod-nls-cp437=y
           CONFIG_PACKAGE_kmod-nls-iso8859-1=y
           CONFIG_PACKAGE_kmod-nls-utf8=y
           CONFIG_PACKAGE_kmod-rt2800-lib=y
           CONFIG_PACKAGE_kmod-rt2800-usb=y
           CONFIG_PACKAGE_kmod-rt2x00-lib=y
           CONFIG_PACKAGE_kmod-rt2x00-usb=y
           CONFIG_PACKAGE_kmod-rtl8192c-common=y
           CONFIG_PACKAGE_kmod-rtl8192cu=y
           CONFIG_PACKAGE_kmod-rtlwifi=y
           CONFIG_PACKAGE_kmod-rtlwifi-usb=y
           CONFIG_PACKAGE_kmod-sched-connmark=y
           CONFIG_PACKAGE_kmod-sched-core=y
           CONFIG_PACKAGE_kmod-scsi-core=y
           CONFIG_PACKAGE_kmod-tun=y
           CONFIG_PACKAGE_kmod-udptunnel4=y
           CONFIG_PACKAGE_kmod-udptunnel6=y
           CONFIG_PACKAGE_kmod-usb-core=y
           CONFIG_PACKAGE_kmod-usb-ehci=y
           CONFIG_PACKAGE_kmod-usb-storage=y
           CONFIG_PACKAGE_kmod-usb-storage-extras=y
           CONFIG_PACKAGE_kmod-usb-storage-uas=y
           CONFIG_PACKAGE_kmod-usb2=y
           CONFIG_PACKAGE_kmod-veth=y
           CONFIG_PACKAGE_kmod-wireguard=y
           CONFIG_PACKAGE_kmod-xradio=y
           CONFIG_PACKAGE_libattr=y
           CONFIG_PACKAGE_libbfd=y
           CONFIG_PACKAGE_libbz2=y
           CONFIG_PACKAGE_libcap=y
           CONFIG_PACKAGE_libcryptopp=y
           CONFIG_PACKAGE_libcurl=y
           CONFIG_PACKAGE_libdevmapper=y
           CONFIG_PACKAGE_libexpat=y
           CONFIG_PACKAGE_libfdisk=y
           CONFIG_PACKAGE_libfreetype=y
           CONFIG_PACKAGE_libjpeg=y
           CONFIG_PACKAGE_libltdl=y
           CONFIG_PACKAGE_liblzo=y
           CONFIG_PACKAGE_libmount=y
           CONFIG_PACKAGE_libncurses=y
           CONFIG_PACKAGE_libnetwork=y
           CONFIG_PACKAGE_libpng=y
           CONFIG_PACKAGE_libreadline=y
           CONFIG_PACKAGE_libupnp=y
           CONFIG_PACKAGE_libwebsockets-full=y
           CONFIG_PACKAGE_libwxbase=y
           CONFIG_PACKAGE_luci-app-amule=y
           CONFIG_PACKAGE_luci-app-aria2=y
           CONFIG_PACKAGE_luci-app-baidupcs-web=y
           CONFIG_PACKAGE_luci-app-diskman=y
           CONFIG_PACKAGE_luci-app-dnscrypt-proxy=y
           CONFIG_PACKAGE_luci-app-dnsforwarder=y
           CONFIG_PACKAGE_luci-app-frpc=y
           CONFIG_PACKAGE_luci-app-guest-wifi=y
           CONFIG_PACKAGE_luci-app-kodexplorer=y
           CONFIG_PACKAGE_luci-app-mwan3=y
           CONFIG_PACKAGE_luci-app-ntpc=y
           CONFIG_PACKAGE_luci-app-openclash=y
           CONFIG_PACKAGE_luci-app-openvpn=y
           CONFIG_PACKAGE_luci-app-openvpn-server=y
           CONFIG_PACKAGE_luci-app-p910nd=y
           CONFIG_PACKAGE_luci-app-passwall=y
           CONFIG_PACKAGE_luci-app-qos=y
           CONFIG_PACKAGE_luci-app-samba=y
           CONFIG_PACKAGE_luci-app-shadowsocks-libev=y
           CONFIG_PACKAGE_luci-app-syncdial=y
           CONFIG_PACKAGE_luci-app-ttyd=y
           CONFIG_PACKAGE_luci-app-udpxy=y
           CONFIG_PACKAGE_luci-app-uhttpd=y
           CONFIG_PACKAGE_luci-app-v2ray-server=y
           CONFIG_PACKAGE_luci-app-verysync=y
           CONFIG_PACKAGE_luci-app-watchcat=y
           CONFIG_PACKAGE_luci-app-webadmin=y
           CONFIG_PACKAGE_luci-app-wireguard=y
           CONFIG_PACKAGE_luci-app-wrtbwmon=y
           CONFIG_PACKAGE_luci-app-xlnetacc=y
          #===========================================================================
           CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
           CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
           CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
           CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
           CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
           CONFIG_PACKAGE_luci-app-ssr-plus=y
          #===========================================================================
           CONFIG_PACKAGE_luci-i18n-amule-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-dnsforwarder-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-guest-wifi-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-kodexplorer-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-ntpc-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-openvpn-server-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-openvpn-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-p910nd-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-qos-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-samba-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-uhttpd-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-v2ray-server-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-verysync-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-watchcat-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-webadmin-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-wireguard-zh-cn=y
           CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
           CONFIG_PACKAGE_luci-lib-httpprotoutils=y
           CONFIG_PACKAGE_luci-proto-wireguard=y
           CONFIG_PACKAGE_luci-theme-material=y
           CONFIG_PACKAGE_luci-theme-netgear=y
           CONFIG_PACKAGE_mount-utils=y
           CONFIG_PACKAGE_mwan3=y
           CONFIG_PACKAGE_nano=y
           CONFIG_PACKAGE_nginx=y
           CONFIG_PACKAGE_ntfs-3g=y
           CONFIG_PACKAGE_ntpclient=y
           CONFIG_PACKAGE_openvpn-easy-rsa=y
           CONFIG_PACKAGE_openvpn-openssl=y
           CONFIG_PACKAGE_p910nd=y
           CONFIG_PACKAGE_parted=y
           CONFIG_PACKAGE_php7=y
           CONFIG_PACKAGE_php7-fpm=y
           CONFIG_PACKAGE_php7-mod-curl=y
           CONFIG_PACKAGE_php7-mod-gd=y
           CONFIG_PACKAGE_php7-mod-iconv=y
           CONFIG_PACKAGE_php7-mod-json=y
           CONFIG_PACKAGE_php7-mod-mbstring=y
           CONFIG_PACKAGE_php7-mod-opcache=y
           CONFIG_PACKAGE_php7-mod-session=y
           CONFIG_PACKAGE_php7-mod-zip=y
           CONFIG_PACKAGE_qos-scripts=y
           CONFIG_PACKAGE_rt2800-usb-firmware=y
           CONFIG_PACKAGE_rtl8188eu-firmware=y
           CONFIG_PACKAGE_rtl8192cu-firmware=y
           CONFIG_PACKAGE_runc=y
           CONFIG_PACKAGE_samba36-server=y
           CONFIG_PACKAGE_smartmontools=y
           CONFIG_PACKAGE_tc=y
           CONFIG_PACKAGE_tcping=y
           CONFIG_PACKAGE_terminfo=y
           CONFIG_PACKAGE_tini=y
           CONFIG_PACKAGE_ttyd=y
           CONFIG_PACKAGE_uclibcxx=y
           CONFIG_PACKAGE_udpxy=y
           CONFIG_PACKAGE_unzip=y
           CONFIG_PACKAGE_verysync=y
           CONFIG_PACKAGE_vim-full=y
           CONFIG_PACKAGE_watchcat=y
           CONFIG_PACKAGE_wireguard-tools=y
           CONFIG_PACKAGE_wireless-regdb=y
           CONFIG_PACKAGE_wpad-mini=y
           CONFIG_PACKAGE_wsdd2=y
           CONFIG_PACKAGE_zoneinfo-asia=y
           CONFIG_PHP7_LIBFREETYPE=y
           CONFIG_SUNXI_SD_BOOT_PARTSIZE=80
           CONFIG_TARGET_ROOTFS_PARTSIZE=1580
           CONFIG_WPA_MSG_MIN_PRIORITY=3
          EOF
          # 
          # ========================固件定制部分结束========================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
                make download -j8 || make download -j1 V=s
                find ./dl/ -size -1024c -exec rm -f {} \;
                df -h
      - name: Compile firmware
        run: |
                make -j$(nproc) || make -j1 V=s
                echo "======================="
                echo "Space usage:"
                echo "======================="
                df -h
                echo "======================="
                du -h ./ --max-depth=1
                du -h /mnt/openwrt/ --max-depth=1 || true
                # - name: Prepare artifact
                #   run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload bin directory
        uses: actions/upload-artifact@master
        if: always()
        with:
                name: OpenWrt_K2P_bin
                path: ./bin

      - name: Upload config.seed
        uses: actions/upload-artifact@master
        with:
                name: config.seed
                path: ./bin/targets/*/*/config.seed

      - name: Remove packages
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
                name: OpenWrt_firmware
                path: ./bin/targets/
